### ISSUE TITLE
Comentários

### ISSUE THREAD

**Issue by campiolo** [dacom-utfpr-cm/atividade-03-monitores-danielbom#1]
ex1:  OK. Sugestão: Productor --> Producer
ex2: OK
ex3: OK
ex4: OK

Os códigos estão corretos, mas a organização dos exercícios está um pouco confusa. Há duas implementações de "main" para cada exercício.

**Comment by danielbom** [comment]
Eu fiz duas implementações mesmo. Durante as atividades percebi um padrão e tentei usar uma implementação mais abstraída. Depois que terminei, achei que a implementação ficou um pouco complexa para se ler, então finalizei o jeito normal de se resolver, tudo de forma separada.
